name: "build-release-cv"

# run on pull requests to develop and master
on:
  push:
    branches: ["master"]

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    container: "leplusorg/latex"
    steps:
      - uses: actions/checkout@v4
        with:
          # check out the feature branch's HEAD
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.push.head.ref }}
          fetch-depth: 0
      # format the latest commit
      - name: Build CV
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra
          xelatex jc_lock_cv.tex
      # Make release and upload file
      - name: Make PDF release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            jc_lock_cv.pdf
